backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "portfolio_data"
    label: "Quản lý dữ liệu"
    delete: false
    editor:
      preview: false
    files:
      - file: "data/music.json"
        label: "Danh sách Sáo Trúc"
        name: "music_list"
        fields:
          - name: "songs"
            label: "Các bài sáo trúc"
            widget: "list"
            allow_add: true
            fields:
              - name: "title"
                label: "Tiêu đề bài nhạc"
                widget: "string"
              - name: "youtube_id"
                label: "YouTube Video ID"
                widget: "string"

      - file: "data/projects.json"
        label: "Danh sách Dự Án"
        name: "project_list"
        fields:
          - name: "projects"
            label: "Các dự án"
            widget: "list"
            allow_add: true
            fields:
              - name: "title"
                label: "Tên dự án"
                widget: "string"
              - name: "version"
                label: "Phiên bản"
                widget: "string"
              - name: "description"
                label: "Mô tả"
                widget: "text"
              - name: "tech_stack"
                label: "Công nghệ"
                widget: "string"
              - name: "image_url"
                label: "Link ảnh"
                widget: "string"
              - name: "download_url"
                label: "Link GitHub/Download"
                widget: "string"
              - name: "web_url"
                label: "Link web"
                widget: "string"
                required: false  
